internalName: izh

locales:
  en:
    name: &bundleName "Ingrian Keyboards"
    description: "Keyboards for Ingrian from the Divvun group at UiT."
  izh:
    name: &bundleName "Ingrian Keyboards (replace with real Ingrian text)"
    description: "Keyboards for Ingrian from the Divvun group at UiT."
  nb:
    name: "Ingriske tastatur"
    description: "Tastatur for ingrisk fra Divvun-gruppa ved UiT."

author: The Divvun Group, UiT Norgga 치rktala코 universitehta
email: feedback@divvun.no

copyright: (c) 2019 Divvun/Giellatekno/UiT
organisation: UiT Norgga 치rktala코 universitehta

layouts:
  - izh-mob
  - izh_FI-mac
  - izh_FI-win

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.izh
    icon: images/izh-icon.pdf
    keyStore: $GTPRIV/admin/dev-accounts/dev_keys/sami_keyboard.keystore
    keyAlias: sami_keyboard

  ios: &AppleID
    codeSignId: "Developer ID Installer: The University of Tromso (2K5J2584NX)"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.izh
    bundleName: *bundleName
    icon: images/izh-icon.png

  osx:
    <<: *AppleID
    icon: images/izh-keyboard-menu-icon.png
    version: 0.1.0
    resources: doc

  win:
    appName: *bundleName
    version: 0.1.0
    url: "http://divvun.no"
    uuid: "B1D43744-C41E-411B-ABC5-B7CBFEDB288B"
